### ISSUE TITLE
UI/UX Desigining

### ISSUE THREAD

**Issue by DevenRathod2** [getify/youperiod.app#11]
I want to contribute to this open-source world-changing project. and I want to work on UI/UX Designing.

**Comment by gioboa** [comment]
Hi @DevenRathod2 in #2 we are talking about a new UI/UX Design

**Comment by DevenRathod2** [comment]
Yeah. i can help you to design a stunning UI 
also @getify can you create a slack workspace for discussion about this project?

**Comment by artmarydotir** [comment]
Hi, i can help too. also have a uterus 😁

**Comment by aditiranka27** [comment]
Hey! I am frontend developer and a I also have a uterus 😁. I would love to help because I had to delete my period tracking apps with these laws and I need something which protects my identity and data. (PS. I live in Texas and female reproductive rights have gone down the the drain here).

**Comment by getify** [comment]
@aditiranka27 I live in Texas too, a big reason motivating this app!

**Comment by aditiranka27** [comment]
@getify I agree! A huge motivation to contribute to something which would help all the people affected.

**Comment by getify** [comment]
I think #2 is tracking the UI design. Do we need a separate thread (this one) just for UX discussions separate from UI, or can we combine our discussion into that other thread?

**Comment by aditiranka27** [comment]
I think we can combine the two threads.

**Comment by getify** [comment]
Great, everyone here, please move over to #2 and jump in! There's a figma project tracking some early design concepts, and plenty more to discuss and decide. Welcome!
