### ISSUE TITLE
App on F-Droid

### ISSUE THREAD

**Issue by artmarydotir** [getify/youperiod.app#22]
I know this is going to be a PWA APP.
i was thinking that we can have a **TWA** from PWA, and since this is going to be open source, we can put it on  F-Droid.
What do you think, can we think about this too?

**Comment by getify** [comment]
I definitely plan to package it as a TWA for the Google Play store. Not sure what Fdroid is, but I would imagine we can publish it there.

**Comment by artmarydotir** [comment]
F-Droid is an app store for Android, similar to the Google Play.
But contains only free and open source apps.

**Comment by getify** [comment]
We'll definitely do this, but there's no work to do right now. Closing for the time being.
