### ISSUE TITLE
Include project roadmap

### ISSUE THREAD

**Issue by AbednegoTM** [getify/youperiod.app#24]
#### Is your feature request related to a problem? Please describe.
There are number of features and processes that have been proposed at a lower level. I believe it is as important to have a high level overview of the project direction. It can help to address certain areas like: 
- High  priority features 
- Features to be worked on next 
- Features currently being worked on 
- Versioning systems
- Timelines 
- Milestones 
- Potential features 
- etc
#### Describe the solution you'd like
For start a simple document describing important project goals and Milestones:
https://mozillascience.github.io/working-open-workshop/roadmapping/

**Comment by artnerdnet** [comment]
good point, we can also use the project tab here on GH to give visibility to the the user stories and who's working on what

**Comment by getify** [comment]
We don't have a roadmap yet. The project is just getting underway.

**Comment by getify** [comment]
Just to clarify, we *will* have a project roadmap eventually... probably in the next 1-3 weeks. I hope that @pselle's work to help us organize what we're doing here will help make that a reality. But since there's nothing immediate to do in this regard, going to close for now.
