### ISSUE TITLE
need a few basic pages

### ISSUE THREAD

**Issue by getify** [getify/youperiod.app#3]
Need an about page, a privacy policy page, maybe a couple of others.

**Comment by kirankok** [comment]
Hi Kyle, would like to work on this.

**Comment by AbednegoTM** [comment]
I can help as well

**Comment by getify** [comment]
Taking some of the wording from the README here, as well as what I said on linked-in, that would be the best starting page for text for a Privacy page and/or About page. So we just need to start drafting that text, and lay it out in basic HTML.

**Comment by Deep1Shikha** [comment]
Shall I start building the privacy policy page?

**Comment by AbednegoTM** [comment]
> Taking some of the wording from the README here, as well as what I said on linked-in, that would be the best starting page for text for a Privacy page and/or About page. So we just need to start drafting that text, and lay it out in basic HTML.

Sounds good as starting point.

**Comment by getify** [comment]
yes! let's coordinate here in issues to minimize how much duplicative work might be done.

**Comment by AbednegoTM** [comment]
> So maybe we should work on agreeing on the text for these pages HERE, before actually building it out in HTML. Probably easier to debate/tweak/improve wording in discussion thread rather than as PRs on top of PRs.

I agree . A contribution guideline may also be needed

**Comment by AbednegoTM** [comment]
Done

**Comment by gkhedekar5758** [comment]
@kirankok and @AbednegoTM I would like to join if you need an helping hand

**Comment by 5hraddha** [comment]
Hey guys @kirankok, @AbednegoTM and @getify! I would like to help as well. Please, let know if there is any page or issue I could help. Thank you!!

**Comment by AbednegoTM** [comment]
_This is draft based on linkedIn Post and about page_

## About  - DRAFT
**A privacy-first period tracking app.**

We could almost all agree that it's never been more important for us to OWN OUR INFORMATION, not governments or "big tech" companies, so that we decide what is done with that information.

I think that especially goes for private medical/health data, of which menstrual tracking (for women / people with uteruses) might just be some of the most sensitive and important to protect.

Companies and apps can *promise* all they want that they're being safe and private with our information. But if they have our information, and they're a company, they're going to have to make money somehow, either by charging us for it, or worse, charging someone else to use it in some way.

We believe this kind of private and sensitive medical information belongs to you, and you alone. As such, YOU. (the app) puts you in control of all your information, and never collects or tracks anything about you, not even your name or email address. Since we don't have any of your data, we obviously CANNOT sell it or hand it over to any governmental authority.

Everything you enter into YOU. (the app) is yours, always and only yours. It stays on your device, protected and secure, and you decide what to do with that information.

This app is free to use, and will remain so forever.

Once installed, this web-app (PWA) runs entirely offline -- only locally on your device, with no need for any internet or to connect to any remote service -- and uses strong cryptography practices to keep your data secure and private on your device, ONLY.

It's built with love and respect, for you, and only about you, and only to help you keep and track your own private health information. That's it. Period.

**Comment by AbednegoTM** [comment]
I am not so strong in writing copy content.  @5hraddha and @gkhedekar5758 I believe this is were you come in Once we done  working on copy I will write the markup. How is that ?
@getify I think the draft above is good starting point for ABOUT page copy.

**Comment by 5hraddha** [comment]
Hi Guys!

Here is the initial draft for **Privacy Policy Page**, based on the LinkedIn Post and Read Me. 

"We believe menstrual tracking (for women/people with uteruses) data might be some of the most sensitive and important data to protect as it belongs to you, and you alone. **You.** (the app) is committed to putting you in control of all your information, and thus, never collects or tracks anything about you, not even your name or email address. Since we don't have any of your data, we obviously _CAN NOT_ sell it or hand it over to any governmental authority.

Everything you enter into **You.** (the app) is yours, and always and only yours. It _stays on your device_, _protected_ and _secure_, and you decide what to do with that information."

@getify @AbednegoTM We could discuss the above initial draft for **Privacy Policy Page**. Once finalized, I could take it up to write the initial markup for this page via a separate PR. Thank you!!

**Comment by gkhedekar5758** [comment]
@AbednegoTM I am also not in content wrting or copy writing, I am a developer so let me know if you need any help where a programmer can help. I am in for any help regarding HTML and JS for any page

**Comment by shambashib20** [comment]
I am also present! I can contribute for Home, About pages as well.

**Comment by aashimaahuja** [comment]
I can also help with the about page. The draft content is already posted up there.

**Comment by AbednegoTM** [comment]
> Hi Guys!
> 
> Here is the initial draft for **Privacy Policy Page**, based on the LinkedIn Post and Read Me.
> 
> "We believe menstrual tracking (for women/people with uteruses) data might be some of the most sensitive and important data to protect as it belongs to you, and you alone. **You.** (the app) is committed to putting you in control of all your information, and thus, never collects or tracks anything about you, not even your name or email address. Since we don't have any of your data, we obviously _CAN NOT_ sell it or hand it over to any governmental authority.
> 
> Everything you enter into **You.** (the app) is yours, and always and only yours. It _stays on your device_, _protected_ and _secure_, and you decide what to do with that information."
> 
> @getify @AbednegoTM We could discuss the above initial draft for **Privacy Policy Page**. Once finalized, I could take it up to write the initial markup for this page via a separate PR. Thank you!!

Looks good , you can use this format . I noticed some parts of the server may use strategies that make use of personal information to protect the same information , that means some sections I have listed below may need to be filled. some May just need a few words like  WE DO NOT COLLECT / TRACK. Just a suggestion open to discussions.

Privacy Policy
Welcome to  YOU .

This policy is effective as of [date].

### Information We Collect
**Log Data**

When You visit the Site, Our servers may automatically log the standard data provided by Your web browser. It may include Your device’s Internet Protocol (IP) address, Your browser type and version, the pages You visit, the time and date of Your visit.

Additionally, if You encounter certain errors while using the Site, We may automatically collect data about the error and the circumstances surrounding its occurrence. This data may include technical details about Your device, what You were trying to do when the error happened, and other technical information relating to the problem. You may or may not receive notice of such errors, even in the moment they occur, that they have occurred, or what the nature of the error is.

Please be aware that while this information may not be personally identifying by itself.

**Personal Information**

**Legitimate Reasons for Processing Your Personal Information**

**Collection and Use of Information**
We may collect personal information from You when You do any of the following on the Site:

Sign up 
Use a mobile device or web browser to access Our content
Contact Us via email, social media, or on any similar technologies
When You mention Us on social media

### Security of Your Personal Information
When We collect and process personal information, and while We retain this information, We will protect it within commercially acceptable means to prevent loss and theft, as well as unauthorized access, disclosure, copying, use, or modification.


### How Long We Keep Your Personal Information

To be filled

### Children’s Privacy

To be filled

### Disclosure of Personal Information to Third Parties

To be filled

### Google Analytics

To be filled

### Controlling Your Personal Information

To be filled

### Use of Cookies

To be filled

### Changes to This Policy
 If We decide to change this privacy policy, We will post the changes here at the same link by which You are accessing this privacy policy.

To be filled

### Consent From You
Where You give Us consent to collect and use Your personal information for a specific purpose. 
To be filled

### Our Legitimate Interests

To be filled

### Compliance with Law

To be filled

### Contact us

To be filled

**Comment by gkhedekar5758** [comment]
I can work on a hamburger menu (css) and have the pages wired up 

About
Privacy
Registration
Login
Dashboard (once logged in)

then we can wire up html behind this menus the actual pages and write up at least for About and Privacy page. Let me know what you all think

**Comment by gkhedekar5758** [comment]
> I can work on a hamburger menu (css) and have the pages wired up
> 
> About Privacy Registration Login Dashboard (once logged in)
> 
> then we can wire up html behind this menus the actual pages and write up at least for About and Privacy page. Let me know what you all think

How about this menu? uploading pictures . we can start with "about us"  and "privacy" page HTML and wire them up behind this. uploading some screenshot. The menu comes up from the top of the screen in transition

let me know how it looks @getify @AbednegoTM @5hraddha @kirankok . Always open to suggestion

![full screen laptop](https://user-images.githubusercontent.com/26604711/177762044-c30d671c-9374-4be2-beb1-e71f76b5f2e1.jpg)
![menu transitiong from above](https://user-images.githubusercontent.com/26604711/177762041-71fc7866-1d57-462a-be69-e33a169dab69.jpg)
![hover over menu](https://user-images.githubusercontent.com/26604711/177762032-59814db5-4e37-4621-bc3a-e8baa44b2ece.jpg)

![ipad min menu](https://user-images.githubusercontent.com/26604711/177762035-4370a6e5-153d-4827-aafa-5113aaef4ad8.jpg)
![phone screen](https://user-images.githubusercontent.com/26604711/177762042-8f0b14ff-7513-4926-ae3f-68d68d40b16e.jpg)
![menu transitiong from above in phone screen](https://user-images.githubusercontent.com/26604711/177762038-8868102f-411d-4e95-b435-f68d57ab8450.jpg)


![hover over menu  phone](https://user-images.githubusercontent.com/26604711/177762046-c85597e8-652d-44e5-b8b6-9d70d1f5523f.jpg)

**Comment by eireann07** [comment]
I have two suggestions: 
1) As someone who has lots of family in medicine, I think we need a clear indication of HIPAA policies (and similar for non-US based users, but starting with HIPAA).
2) Related to the educational section about menstruation: As a menstruator, I can confidently tell you that something we're never told is hour various contraceptives interact with our periods. I feel that is extremely important. 

Happy to help writing the content for both!

**Comment by jsonjunkie** [comment]
anywhere i can jump in on this or is this issue completely covered? also is there something like a kanban/trello board?

**Comment by biswajitxxxx** [comment]
Okk

**Comment by getify** [comment]
@eireann07 thanks for the suggestions. I especially like the idea of good educational text, or at least links pointing users to good sources.

Regarding HIPPA:

1. I recently learned that HIPPA strangely and disturbingly does not apply to things like period trackers, personal fitbits/health trackers, etc. Since the law doesn't cover any of the kinds of data this app collects, I don't think we need to concern ourselves with either compliance or even statement of its status. Doing so might actually mislead or confuse our users.

2. Since this app *never* sends any data anywhere besides your device, I think the concept of HIPPA laws (in any jurisdiction) wouldn't even apply. Our privacy policy will state we don't ever see your data, and further that we take steps to keep the data on your device encypted and protected. While there's no legal aspect to such a statement, I think that stance (and the auditability of the code to prove it) is far stronger than the protections any law could ever give users.

----

BTW, I feel similarly about GDPR type laws. There's no data processors, and since you control your data, you can delete the only copy/copies of it any time you want.

**Comment by getify** [comment]
@jsonjunkie (and everyone else)... 

the project is still early self organizing. Not yet any official work assignments or project roadmaps or anything like that.

The issues list, and GH discussions list, is currently the source of truth for what work we're discussing, and what tasks we're tackling.

If younsee something you think needs to be done, and want to do it, please just do so. There's no official permission or authority control in place yet.

I have appointed @pselle to begin formalizing some of the organizing processes, so more will solidify in that respect in the coming days/weeks. But... this is open source, not a company. We mostly will self-organize and evolve as we go.

So expect a certain level of informality to continue, and please exercise good judgment and cooperation to communicate/coordinate with others to share the task load.

**Comment by pselle** [comment]
Hi all! I'm closing this issue and creating more specific issues so they can be picked up more easily. Please see issues linked to this one for contributing!
