### ISSUE TITLE
Use GitHub Discussions to build the community

### ISSUE THREAD

**Issue by nemanjaglumac** [getify/youperiod.app#30]
#### Is your feature request related to a problem? Please describe.
People will have a lot of questions about this project as it starts growing. Both the contributors and the potential users of the app. Using Slack for discussion is a common practice but it has many downsides and can be overwhelming for people who are not used to using it.

Also, if the key value of this app is privacy, Slack is probably not the best idea.

#### Describe the solution you'd like
Enable GitHub Discussions for this project to start building the community and the body of knowledge.

#### Describe alternatives you've considered
- [Mattermost](https://mattermost.com/) is almost identical to Slack but it is OSS
- [Twist](https://twist.com/home) is an amazing Slack alternative and is much better suited for async communication

#### Additional context
In general, I'd suggest using the full GitHub ecosystem (wiki, projects, discussions, actions...). This is an OS project and as such it is eligible for a pretty generous free packages that GH offers.

**Comment by getify** [comment]
Just curious your thoughts... How will having discussions out in the open be "more secure" than say on an invite-only discussion board like slack?

**Comment by nemanjaglumac** [comment]
Those are two separate topics and I might have introduced a confusion by even mentioning privacy here.

Basically wanted to say that I wouldn't put trust in Slack as a company when it comes to the privacy. However, they are the go-to tool for the huge majority of eng projects, so... it makes sense to gravitate towards that solution.

As the title suggests, using GitHub Discussions is helpful in building (and nurturing) the community. That part had nothing to do with the security or the privacy.

Sorry for the confusion.

**Comment by getify** [comment]
Got it. Thanks for the clarification, was hoping to make sure I hadn't missed something.

With respect to "Github Discussions"... what does that feature entail (I'm not familiar with it)? How do you see it working differently from the issue threads we have already? Same questions with wikis and/or GH pages?

I'm generally quite happy and willing to use all these various GH features, but I would like to have a clear and defined plan and reason for each, with an obvious and stated goal in mind. What I'd like to avoid is the overwhelm of additional *options* (thus complexity) where we are having meta debates about "should this conversation be in X, Y, or Z different places", if that makes sense.

I'm eager to hear your thoughts on how we can use these various GH tools better.

**Comment by nemanjaglumac** [comment]
### Discussions

> With respect to "Github Discussions"... what does that feature entail (I'm not familiar with it)?

Here's [Discussions page](https://docs.github.com/en/discussions) with a 60s video explainer.

And this quote is from a [quickstart page](https://docs.github.com/en/discussions/quickstart#welcoming-contributions-to-your-discussions):
> Discussions are for conversations that need to be transparent and accessible but do not need to be tracked on a project board and are not related to code, unlike GitHub Issues.

Many non-technical users do not really understand "issues", but mostly everyone is familiar with forums / BBs / chat groups.

Discussions have threaded responses, for example and you can mark questions as answered.
They might be a much better place for freeform conversation that is not necessarily related to any technical aspect of this repo.

Maybe it's best seeing the real-world examples: https://github.blog/2022-01-13-how-five-open-source-communities-are-using-github-discussions/

> What I'd like to avoid is the overwhelm of additional options (thus complexity) where we are having meta debates about "should this conversation be in X, Y, or Z different places", if that makes sense.

Totally.
TIL that you can convert issues to discussions and vice versa, if that alleviates any of these concerns.

### Wiki
Probably not going to be needed for the project of this size. A couple of well defined markdown docs will do the work.
If their number starts rising and you find yourself having to link between them, that's a good sign that the Wiki page is needed to keep tech knowledge organized.

### GH pages
Never mentioned them.

### GH Actions
Any process that needs to be automated.
But the most likely (and the most useful) scenario will be for running tests to ensure there are no breaking changes.

**Comment by getify** [comment]
> Discussions have threaded responses, for example and you can mark questions as answered.
They might be a much better place for freeform conversation that is not necessarily related to any technical aspect of this repo.

OK, got it. Let's try it out here. I just converted this to a discussion: https://github.com/getify/youperiod.app/discussions/36

**Comment by nemanjaglumac** [comment]
https://github.com/getify/youperiod.app/issues/5 seems like a good candidate for an "💡 Idea" category in discussions.

**Comment by getify** [comment]
OK, I've converted several threads to discussions. Let's see how that goes, and we can perhaps revisit this after a bit to see if we like the direction or not. :)
