### ISSUE TITLE
Need more info on what project is about.

### ISSUE THREAD

**Issue by piterjov** [getify/youperiod.app#43]
I don't know if I'm missing something, but cannot find a page about what the project does exactly?

Thanks

**Comment by piterjov** [comment]
Thanks, guys, I was thinking more of the vision and goals of the app.

**Comment by getify** [comment]
From the linked-in post where I first announced this project:

> Regardless of your politics or how you view certain hot-button social issues (especially in the US right now), I think we could almost all agree that it's never been more important for us to OWN OUR INFORMATION, not governments or "big tech" companies, so that we decide what is done with that information.
>
> I think that especially goes for private medical/health data, of which menstrual tracking (for women / people with uteruses) might just be some of the most sensitive and important to protect.
>
> Companies and apps can *promise* all they want that they're being safe and private with our information. But if they have our information, and they're a company, they're going to have to make money somehow, either by charging us for it, or worse, charging someone else to use it in some way.
>
> The only solution I see is for an app that never gives that information away, period. An app that keeps all that information *only on your device*, and encrypts it, and that's it. Your data, yours, on your device(s), in your control. Nothing more. A privacy-first period tracking app.
>
> I call it "You." (as in "you period"). It's built with love and respect, for you, and only about you, and only to help you keep and track your own private health information. That's it. Period.

**Comment by gioboa** [comment]
I think we can add this description in the README.md to explain what the application does

**Comment by getify** [comment]
I think most of the info necessary to explain the project is in the README, and I think other supporting docs (like the specs, the technical philosophy writeup, and even the contribution guidelines) help fill in the details.

There will eventually be a "product roadmap" which will help, too. But for now, I don't think there's more work to do on this issue, so closing for the time being.
