### ISSUE TITLE
Add Privacy Policy page

### ISSUE THREAD

**Issue by pselle** [getify/youperiod.app#50]
Add a privacy policy page. This issue: https://github.com/getify/youperiod.app/issues/3 has some initial copy suggestions.

If you would like to work on this issue, please go ahead and open a PR, ensuring your PR mentions "closes #50 "

**Comment by asheerrizvi** [comment]
Do we have some rough draft for the contents of this page? The text within #3 looks incomplete.

**Comment by pselle** [comment]
Nope, there is no other document. Feel free to research and propose in a PR!
