### ISSUE TITLE
Add a prettier configuration file

### ISSUE THREAD

**Issue by rzvl** [getify/youperiod.app#56]
Since each developer uses a different style to format his/her code, the code may look more and more inconsistent as the project grows.

I think having a prettier config file, at these early stages, would help to keep the code consistent and more readable in future.

**Comment by getify** [comment]
This has already been discussed, please search the closed issues/prs.

**Comment by rzvl** [comment]
Oh yes. I see it now! Sorry, I didn't notice that...

**Comment by rzvl** [comment]
done

**Comment by getify** [comment]
We may revisit later, but closing for now. Thanks.
