### ISSUE TITLE
Contribution guideline is needed 

### ISSUE THREAD

**Issue by AbednegoTM** [getify/youperiod.app#6]
For better collaboration a contribution guideline will be needed as a reference.

**Comment by getify** [comment]
Yes, definitely.

I'll start:

1. We need a code-of-conduct (perhaps basic text from a good web conference's CoC) for respect of contributors
2. We need statement that all contributions of code or documentation are open-source licensed under MIT

**Comment by AbednegoTM** [comment]
How is this for a start in terms of code of conduct. 
 - https://www.contributor-covenant.org
 - https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.txt
 with regards guidelines I do believe it will be a living document which will get updated as we go.

**Comment by asheerrizvi** [comment]
Should we discuss PR and issue templates here as well? Someone opened as issue for this.

**Comment by prabhpreet-code** [comment]
Actually, I remember I saw some contribution guidelines in one of the projects so attaching them here If you think they could be of any help?? 
*****************************************************************************

# Contribution guidelines 🔐

**Hello contributors, i want you to stick to the below-listed contribution guidelines. Happy contributing.**

<br/>

- Issues will be assigned on a First-Come-First-Serve basis and are applicable only when they opt through GitHub.
- Each issue needs to be completed within a specific time limit according to its difficulty level ( **`Easy`: 1 day, `Medium`: 2-3 days, and `Hard`: 4 days )**.
- If a mentee is unable to solve the allotted issue within the given period, the issue needs to be passed to other contenders at the discretion of the mentor.

- You will be performing changes to **ABC** branch ONLY.
- `Fork` the repo to your account.
- `git clone` to clone the repo

- Make your desired changes to the code ,
- Make sure you do `git pull` to pull the latest version of the code
- `git add .` to stage for commits
- **NOTICE--> message will be `fix: <anything you fixed>`**
- `git commit -am "fix: Updated bla bla bla"` for committing the code.

  <br/>

- Then create a Pull Request and wait for review.
- Pull request title: **`fix: bla bla bla`** , essential to pass the checks.
- Don't forget to attach **`Screenshots, Proper Description and Issue Number`**
- Remember to be respectful to other contributors, mentors, community
- Don't raise invalid/spam issues they will be closed !!

<br/>

---

<br/>

**You'll need to follow the [Setup Guidelines]() for more details on setting up the code in your local machine**

**Comment by getify** [comment]
A lot of this is good. I don't think we need to overburden contributors with time frames or any of that sort of thing. The project is small and we don't have any of those problems (nor do I anticipate them), so let's simplify and remove the time frame stuff.

**Comment by ricardoaguiar** [comment]
How about branches? Are we going to create feature branches to dev and then to main?

**Comment by getify** [comment]
@ricardoaguiar good question. we probably do eventually want some standardization of such process, but it's maybe too early to be too detailed/prescriptive.

Perhaps a general statement like added like: all code work is done in branches, with PRs and reviews, and core project maintainers are responsible for merging into the main trunk.

**Comment by rpalaciosg** [comment]
@prabhpreet-code I want to add, I think it is important to have a good syntax in the commit messages following 
[Conventional Commits](https://www.conventionalcommits.org/), you could add husky to validate this with git hooks in pre-commit. I think it would be good to do it now that the project is starting.

**Comment by emmanuelonah** [comment]
Was not sure where to comment this; I think we need a conversation thread 🧵 under the issue section where people can suggest what they think be in the system. That way everybody do not create an issue. Because so far, I have seen that the issue are create by **Kyle** and that makes sense to me. So if this makes sense, I suggest Kyle should create a thread title **idea/feature suggestions**

**Comment by emmanuelonah** [comment]
> Was not sure where to comment this; I think we need a conversation thread 🧵 under the issue section where people can suggest what they think be in the system. That way everybody do not create an issue. Because so far, I have seen that the issue are create by **Kyle** and that makes sense to me. So if this makes sense, I suggest Kyle should create a thread title **idea/feature suggestions**

This are base feature I think we should also have:

1. Before contributions get far, let's setup eslint, prettier and husky. 
  Eslint - for code structure enforcement (we could use Airbnb or any other)
  Prettier - for code structure correction 
  husky - to ensure code style is followed before living developer machine to GitHub server


2. I suggest we build our reusable accessible navigation template for other pages to consume(personally I like w3c accessibility guideline)

I think this are primary features needed ASAP

**Comment by prabhpreet-code** [comment]
@ricardoaguiar sorry to inform you that am not well-versed in using husky... so you are good to go to implement it. Till then I would also love to learn more about it :)

**Comment by emmanuelonah** [comment]
@rpalaciosg apart from husky, I think having both eslint and prettier is necessary

**Comment by artnerdnet** [comment]
> @rpalaciosg sorry to inform you that am not well-versed in using husky... so you are good to go to implement it. Till then I would also love to learn more about it :)

I have experience with husky so I can help too, and I can start by setting up eslint and prettier

**Comment by emmanuelonah** [comment]
@artnerdnet cool, let's wait to hear from @getify on which eslint coding standard to use.

**Comment by rpalaciosg** [comment]
Hi @artnerdnet, depending on what Kyle says about this, how about if I work on the husky configuration and you work on the prettier and eslint part? I was working on a PR.

**Comment by getify** [comment]
I shared thoughts on this topic in #29. We should probably consolidate discussions of this into one thread or the other, to prevent fragmentation of thoughts.

**Comment by getify** [comment]
Another thing to add to the contributions guidelines is to have contributors [review this writeup](https://github.com/getify/youperiod.app/discussions/36) for the technical decision making philosophy/principles that I'm currently applying to shepherding this project. It's important that all contributors understand the underlying reasonings and that they roughly agree to abide by them for the current state of the project.

Also, it should be mentioned that this is only the *current* project philosophy/governing ideals, and that *that guidance* will evolve over time, both as the project matures and as others step up into more ownership roles within the project and I delegate my project leadership authority to them.

**Comment by getify** [comment]
Let's aim to have the contributor guidelines 1.0 solidifed by EOD tomorrow (Fri July 8), so that by early next week ideally we have everyone involved here having reviewed and agreed to it. We'll probably do so via a "Poll" feature under github discussions, where we just ask everyone to read the guidelines and then "vote" that they agree.

**Comment by getify** [comment]
We have the code-of-conduct rolled out, so that's a big step.

Let's try to finalize the rest of the contribution guidelines soon. Who's working on what in that respect?

**Comment by pselle** [comment]
I opened a PR with a CONTRIBUTING.md. It seems most of the discussion here was related to Code of Conduct, which is solved, so the file added is very lightweight.
