### ISSUE TITLE
For slightly more security, apply CSP policy for worker script

### ISSUE THREAD

**Issue by getify** [getify/youperiod.app#67]
Since web workers (loaded from separate files instead of inline blobs/data-uris) ***do not respect*** the hosting document's CSP policy, they are potentially slightly less secure. There's a way to fix that though:

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#content_security_policy

Need to have [`server.js` (around this line)](https://github.com/getify/youperiod.app/blob/cb1935ce3384529ee31b1d0b7be47a1c8c9cc64d/server.js#L151) check for the request for "auth-worker.js", and to set a specific CSP just for that worker response -- a derivative subset of [this base CSP policy](https://github.com/getify/youperiod.app/blob/cb1935ce3384529ee31b1d0b7be47a1c8c9cc64d/server.js#L24-L46), but in particular setting the `script-src` to include only `self` and [`wasm-unsafe-eval`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_webassembly_execution).

**Comment by bbland1** [comment]
So I was looking at this and thinking would it be like a:
```
if (req.headers["referer".includes("auth-worker")) { // do the CSP setting in the response header} 
```

This was my initial thought but it felt very basic and I'm not fully sure if that would properly check if the req is using the auth worker.

**Comment by getify** [comment]
I think just `req.url == "auth-worker.js"` should work.
